language: java
sudo: required
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker
script:
- docker-compose -f docker-compose-travis.yml up -d
before_install:
- openssl aes-256-cbc -K $encrypted_18e83bea543e_key -iv $encrypted_18e83bea543e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
