language: java

sudo: required

branches:
  only:
  - deploy

cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
services:
- docker

script:
  - docker-compose -f docker-compose-travis.yml up --exit-code-from app

addons:
  ssh_known_hosts:
   - liziyi.top

before_install:
- openssl aes-256-cbc -K $encrypted_18e83bea543e_key -iv $encrypted_18e83bea543e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
  - chmod 600 ~/.ssh/id_rsa
  - ssh travis@liziyi.top "/home/travis/attnd_start.sh | tee /home/travis/log_attnd/log"